server:
  port: 9091
spring:
  zipkin:
    enable: true
    base-url: http://localhost:9411
    service:
      name: product-service
  data:
    mongodb:
      host: 34.159.164.225
      port: 27777
      database: Java4Db
      username: root
      password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


