server:
  port: 8888
spring:
  zipkin:
    enable: true
    base-url: http://localhost:9411
    service:
      name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo
